### PR TITLE
PRIO-2 style|chore: Introduce checkstyle in build, reformat accoding to TX Style Guide

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

This PR introduces the TX style guide (mainly: Java) and rechecks DEPENDENCIES with an updated eclipse dash tool.

## WHY

Developers from tractus-X could be confused to read code that was only checked using spotless without any specific rules.

## FURTHER NOTES

see https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/57 and
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/76 for our sibling repository.

### CODE REVIEW

**Comment by carslen** [comment]
Can one, who is not @drcgjung, confirm, that this is only a reformatting PR? With that approval, I'd not open a EF IP-Check based on the amount of changed code lines...

**Comment by carslen** [comment]
@Martin0815bla you also confirm, that this PR is only reformating, no new code? This is important for opening a IP Check or not.

**Comment by Martin0815bla** [comment]
According to my review there is no new functionality implemented but rather a rework and beautification of existing code

**Review by carslen — APPROVED** [review]
LGTM. 
According to @Martin0815bla it's only reformating the code.

**Pull request merged**
