### PR TITLE
feat: upgrade matchmaking agent to interact with edc 0.7; complete chart/deployment

### LINKED ISSUE #53: Story "Implement Matchmaking Agent API"
# Story "Implement Matchmaking Agent API"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA EDC developer, I want to have an implementation of the Matchmaking API in order to program against it.

## Acceptance Criteria

- carved out code from https://github.com/catenax-ng/knowledge-agents-edc (agent-plane/src/main/.../sparql and agent-plane/src/main/.../rdf) to extend skeletons (controller)
- unit tests for the most common use cases

## Estimation 

10 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/276#issuecomment-1770752608_

### LINKED ISSUE #54: Story "Define Matchmaking Agent API"
# Story "Define Matchmaking Agent API"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA developer, I want to have a REST API that may be used as the interface between the EDC data/agent-transfer plane and the matchmaking agent in order to implement or program against it.

## Acceptance Criteria

- open API definition
- stubs (client) and 
- skeletons (controller)

## Estimation 

3 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/276#issuecomment-1770747516_

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

The Matchmaking Agent is now able to interact with
- TX EDC Control Plane 0.7.*
- Knowledge Agent Plane 1.12.>19

## WHY

The Matchmaking Agent has been carved out of Knowledge Agent Plane 1.11.16 (24.03) which run against TX EDC 0.5.*
This PR contains the necessary adaptions and bugfixes following the 24.05 E2E Test phase.

## FURTHER NOTES

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

Closes #54 
Closes #53

### CODE REVIEW

**Comment by almadigabor** [comment]
Hi @drcgjung, I've ran the dash tool and got the following output:

```
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-rdfpatch/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14714 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-core/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14700 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-tdb2/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14701 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-fuseki-core/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14702 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-rdfconnection/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14703 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-dboe-storage/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14704 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-dboe-base/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14705 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-shacl/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14706 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-dboe-trans-data/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14707 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-tdb/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14708 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-shex/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14709 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-dboe-index/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14710 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-arq/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14711 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-dboe-transaction/4.9.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14712 .
```

Let's wait until the afternoon for these to be resolved then I can review and merge your PR. You might need a DEPENDENCIES file update once the IP issues are closed.

**Comment by almadigabor** [comment]
Hey @drcgjung, can you update the dependencies file? If I see it correctly, all issues have been approved.

**Comment by drcgjung** [comment]
> Hey @drcgjung, can you update the dependencies file? If I see it correctly, all issues have been approved.

@almadigabor done and successful. thx.

**Comment by almadigabor** [comment]
I opened an IP review issue due to the large number of changes. Please track the status [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14722).

**Comment by drcgjung** [comment]
actually the current lint test failure is a fluke: https://github.com/catenax-ng/tx-knowledge-agents/actions/runs/9110519613/job/25045730604
seems like some rare timing/kind issue occured - could not reproduce it. so maybe simply restart the failted check/job and it should go through.

**Comment by almadigabor** [comment]
The IP check issue have been approved.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
