### PR TITLE
fix(provisioning|remoting): address some updates in the case of non-standard base images

### LINKED ISSUE #72: Fix: Upgrade/Exchange Base Images
# Observation (As-Is)

Current Base Images for conforming-agent, remoting-agent and provisioning-agent lack behind (os package-wise) and have three different sources (temurin, tomcat & ubuntu).

# Goal (As-Should)

Use the same up-to-date base image (temurin)

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Upgrade dependencies to parent/root OSS projects (RDF4J, Ontop)
Switch to standard base images by using a build stage (provisioning-agent) or an alternative tomcat installation (remoting-agent).
Upgrade security-relevant packages, remove unused packages 

## WHY

Stay with most recent dependencies.
Fix recent HIGH findings apparent in the RDF4J-SDK and Ontop runtimes.
Make images release guideline compliant.

## FURTHER NOTES

Two IP checks need to be issued as a result.

maven/mavencentral/org.apache.tomcat/tomcat-annotations-api/9.0.84, , restricted, clearlydefined
maven/mavencentral/org.locationtech.jts/jts-core/1.18.2, NOASSERTION, restricted, clearlydefined

Closes #72

### CODE REVIEW

**Comment by drcgjung** [comment]
see https://github.com/eclipse-tractusx/knowledge-agents/pull/66 there is something strange going on with the ECA check.

**Review by Martin0815bla — COMMENTED** [review]
Mostly version changes reviewed.

**Review by Martin0815bla — COMMENTED** [review]
Predominantly Tomcat version changes and UserID changes reviewed

**Comment by drcgjung** [comment]
@SebastianBezold we finally managed to get rid of all non-base images! Martin reviewed already and the stuff was already integration tested.

**Review by carslen — APPROVED** [review]

**Pull request merged**
