### PR TITLE
fix: Provisioning Agent Ontology Configuration & JRW Compatibility with Dremio Drivers

### LINKED ISSUE #81: Provisioning Agent (Regression): When configuring multiple mappings/endpoints all but the last one get the right ontology.
### Current Behavior

When configuring several endpoints

Found 5 endpoints to provide under --cors-allowed-origins=* --lazy.Providing endpoint 1 on port 8084 with ontology /opt/ontop/input/cx-ontology-minimal.ttl mapping /opt/ontop/input/rul.obda properties /opt/ontop/input/settings.dremio.properties portal /opt/ontop/portal.toml dev mode false and tool optionsInvoking intermediate processProviding endpoint 2 on port 8081 with ontology /opt/ontop/input/cx-ontology-minimal.ttl mapping /opt/ontop/input/hi.obda properties /opt/ontop/input/settings.dremio.properties portal /opt/ontop/portal.toml dev mode false and tool optionsInvoking intermediate processProviding endpoint 3 on port 8082 with ontology /opt/ontop/input/cx-ontology-minimal.ttl mapping /opt/ontop/input/trace.obda properties /opt/ontop/input/settings.dremio.properties portal /opt/ontop/portal.toml dev mode false and tool optionsInvoking intermediate processProviding endpoint 4 on port 8083 with ontology /opt/ontop/input/cx-ontology-minimal.ttl mapping /opt/ontop/input/quality.obda properties /opt/ontop/input/settings.dremio.properties portal /opt/ontop/portal.toml dev mode false and tool optionsInvoking intermediate processProviding endpoint 5 on port 8080 with ontology /opt/ontop/input/cx-ontology-minimal.ttl mapping /opt/ontop/input/dtc.obda properties /opt/ontop/input/settings.dremio.properties portal /opt/ontop/portal.toml dev mode false and tool optionsInvoking last process

all but the last endpoint is setted up correctly with the correct ontology and mapping
 
Error: Found unexpected parameters: [/opt/ontop/input/cx-ontology-minimal.ttl, /opt/ontop/input/dtc.obda]Run `ontop help endpoint` to see the help for the command `endpoint`Error: Found unexpected parameters: [/opt/ontop/input/cx-ontology-minimal.ttl, /opt/ontop/input/dtc.obda]Run `ontop help endpoint` to see the help for the command `endpoint`Error: Found unexpected parameters: [/opt/ontop/input/cx-ontology-minimal.ttl, /opt/ontop/input/dtc.obda]Run `ontop help endpoint` to see the help for the command `endpoint`Error: Found unexpected parameters: [/opt/ontop/input/cx-ontology-minimal.ttl, /opt/ontop/input/dtc.obda]Run `ontop help endpoint` to see the help for the command `endpoint`

### Expected Behavior

The endpoints should start with their assigned ontology and mapping.

### Steps To Reproduce

see https://github.com/catenax-ng/product-knowledge/blob/release/1.11.16/infrastructure/templates/oem-provider.yaml

### LINKED ISSUE #82: Provisioning Agent: Java Version Incompatible with Dremio JDBC Driver's Network Stack
### Current Behavior

When configuring a data source using the Dremio JDBC Driver, the provisioning agent will not deliver any data because of network exceptions. Basically, the socket communication runs into a closed buffer.

### Expected Behavior

Data sources with dremio's jdbc driver (and similar drivers using the same network stack) should be compatible with the Java version that the provisioning agent exhibits.

### Steps To Reproduce

1.11.16-SNAPSHOT / main

see https://github.com/catenax-ng/product-knowledge/blob/main/infrastructure/oem/resources/settings.dremio.properties

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

This fix resolves two issues with the provisioning agent which appeared during the E2E Test 24.03 (shell script & JRE platform).
It also documents the version changes (on logback) and hardening efforts (on spring web) between the 1.10 and 1.11 lines.
Some github actions have been upgraded, too.

## WHY

Due to an erroneous command line, the ontology configurations were not taken from the environment variables correctly for all endpoints but the last.
Furthermore, when working against a virtualizer, such as dremio, the jdbc drives included in the image need to be compatible with the JRE version (else their network stack could run into connection problems).

## FURTHER NOTES

Dremio switched their driver model in a later/more current version from a proprietary to an open-source based generic one.
We should have a look at that for the 1.12.x line/24.05

Closes #81 
Closes #82

### CODE REVIEW

**Review by Martin0815bla — APPROVED** [review]
Version change reviewd

**Comment by drcgjung** [comment]
@carslen would you be so kind to "adopt" this PR ... it would be needed for getting SAST approval.

**Comment by drcgjung** [comment]
@almadigabor it would be wonderful, if you could take over this PR ...

**Review by carslen — APPROVED** [review]
LGTM

**Pull request merged**
