### PR TITLE
docs|fix|chore(provisioning-agent): SAST Flaws and CHANGELOG

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Addressed four issues from SAST (2*XSLT External Entity Disablement, 2*Discrepancy between unclean maven deps and clean docker runtime)
Already reference upcoming release in CHANGELOG
Include a cloud-based postgres test which reflects a valid deployment scenario (and its current pitfalls).

## WHY

CHANGELOG should reflect release status (TRG)
Render SAST analysis green and close to 100%
include test settings from E2E tests.

### CODE REVIEW

**Review by the-tatanka — COMMENTED** [review]
In your docker file _provisioning/src/main/docker/Dockerfile_ you change the permission to 755. I think just the ontop user needs executable permission. Maybe chmod 700 is sufficient enough.

**Comment by the-tatanka** [comment]
I also added some security docs to your XMLProvider class - makes it easier to understand.
Stylesheet and DTD checks look good :)

**Comment by the-tatanka** [comment]
**For extra points** - you could validate the XML to a schema. This is the best way to prevent XML injection attacks. 
No pressure :)

**Comment by drcgjung** [comment]
> **For extra points** - you could validate the XML to a schema. This is the best way to prevent XML injection attacks. No pressure :)

Good point:

https://github.com/eclipse-tractusx/knowledge-agents/issues/32

**Review by SebastianBezold — APPROVED** [review]

**Review by the-tatanka — APPROVED** [review]

**Pull request merged**
