### PR TITLE
chore: add automated DAST scanning (courtesy of @RoKrish14).

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

This PR introduces automated (and manual) DAST scanning using ZAP.

## WHY

Manual DAST scanning is a tedious but critical effort. ZAP can be automated to perform these scans regularly and give more immediate feedback. 

## FURTHER NOTES

Please set the following (repository) secrets before activating/merging this PR (by personal communication with the requestor)

image

### CODE REVIEW

**Review by Martin0815bla — CHANGES_REQUESTED** [review]
- Copyright year not set to 2024 in kics.yml
- Still github code 5 check failures in openapi.json (Array Without Maximum Number of Items (v3) Array schema has 'maxItems' set)

**Review by Martin0815bla — APPROVED** [review]
Flawless now

**Review by RoKrish14 — APPROVED** [review]
LGTM 👍

**Comment by drcgjung** [comment]
if I understood it right, DAST is no more part of the release Q-gates (since there will not be a scannable environment anymore).

**Pull request closed without merging**
