### PR TITLE
fix: problems with busybox default shell on linux/amd64. 

### LINKED ISSUE #75: Provisioning Agent Chart (main): chart test fails.
### Current Behavior

chart test fails

https://github.com/eclipse-tractusx/knowledge-agents/actions/runs/7784112459

### Expected Behavior

chart test successful

### Steps To Reproduce

Run ct locally with the https://hub.docker.com/layers/tractusx/provisioning-agent/1.11.16-SNAPSHOT/images/sha256-2d14a83dc4f1ac5619ae60f928db3bba2264fff066fd9a6b01c14493c5af9778?context=explore

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

need to port entrypoint script to ash expressions as busybox alpine will not be bash compatible.

## WHY

curently the chart test fails (without special configuraton or mount overrides).

## FURTHER NOTES

Closes #75

### CODE REVIEW

**Comment by drcgjung** [comment]
@carslen, sorry there was a platform-dependent base image incompatibility (regarding the available shell syntax). We fixed that so that the chart test should go through now.

**Review by carslen — COMMENTED** [review]
Please check and update Copyright headers:
- New files shoud start with 2024 and not in the past as they did not exists back then
- update range of years in changed files (2022, 2023 → 2022, 2024)
- add an empty new line to the end of the files

**Review by Martin0815bla — CHANGES_REQUESTED** [review]
Please check on the comments from Carsten Lenz regarding Copyright headers.

**Review by Martin0815bla — APPROVED** [review]
New Copyright regulations have been inserted

**Comment by drcgjung** [comment]
@carslen thanks for the heads up. copyright headers and newlines have been adapted.

**Review by carslen — APPROVED** [review]
LGTM now

**Pull request merged**
